### ISSUE TITLE
[JOSS Review] Add JOSS badge to README 

### ISSUE THREAD

**Issue by fawda123** [USEPA/SSN2#11]
Minor suggestion, but consider adding the JOSS badge to the package readme.  Currently this indicates in review, but would include the full DOI when published. 

https://github.com/openjournals/joss-reviews/issues/6389

**Comment by michaeldumelle** [comment]
Thanks @fawda123. Incorporated in [this commit](https://github.com/USEPA/SSN2/commit/23200926c0582c4cf7c70e116df372c0e26cf8c3) and available in README.md on the develop branch.
