### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by k-doering-NOAA** [USEPA/SSN2#16]
A few small pieces of the Documentation parts of the [checklist](https://github.com/openjournals/joss-reviews/issues/6389#issuecomment-1995867057) are missing:

- The statement of need on the readme is missing who the target audience is (it is hinted at, but not said explicitly)
- For community guidelines, there is no information on the readme about how to seek support (contributing and reporting issues is covered on the readme/by the CONTRIBUTING.md file)

**Comment by michaeldumelle** [comment]
Thanks @k-doering-NOAA! I added the following to the statement of need in the journal article and in the README (on the develop branch), which now reads "The `SSN2` **R** package is designed to help users fit SSN models to their stream network data." How is this? I also added a `CONTRIBUTING to SSN2` section to the top of the README, just after `Installation Instructions`. The relevant commit is [linked here](https://github.com/USEPA/SSN2/commit/c7671c24f3a2a760a5f0e27bdb9e791092ba7bc4).

**Comment by k-doering-NOAA** [comment]
@michaeldumelle the target audience looks good!

I still feel like the "seek support" piece is missing from the readme (although how to contribute is covered well) - what should users do if they need help using SSN2 or discover what they think is a bug? Maybe just one sentence on the readme under the contributing section (or a "getting help" section) could address this?

**Comment by michaeldumelle** [comment]
@k-doering-NOAA I totally agree; thanks for pointing this out! How do the new `Contributing to SSN2` and `Getting Help` sections in the README (on develop) from [this commit](https://github.com/USEPA/SSN2/commit/15aad49b7a34c9f6bd8773727d293c88495ca433) look?

**Comment by k-doering-NOAA** [comment]
This looks great! I think from my perspective, this issue can be closed out, and I'll check off the last remaining JOSS review checklist item. Thanks @michaeldumelle!

**Comment by michaeldumelle** [comment]
I'll go ahead and close out the issue. Thanks again @k-doering-NOAA !
