### ISSUE TITLE
suggestion: roxygen documentation for non-exported functions

### ISSUE THREAD

**Issue by k-doering-NOAA** [USEPA/SSN2#17]
This is only a non-blocking suggestion to help with maintenance in the future.

I noticed some functions that aren't exported are missing roxygen documentation. For example,

https://github.com/USEPA/SSN2/blob/6b634c5ac1ce66195db5cbdec6c9ac3d10bee46a/R/amongSitesDistMat.R#L1-L4

The comments on lines 2-4 could instead be turned into roxygen documentation, which would be more explicit about what the function does and what the variables are. This can benefit future maintainers so it is easier to remember (or learn for the first time) the purpose of the function.

**Comment by michaeldumelle** [comment]
Thank you for the feedback @k-doering-NOAA! I will respond in this post which I will edit as I progress through documenting non-exported functions. Please reach out if you have any questions/comments/concerns!

We have added roxygen documentation for all non-exported functions, which includes functions in:

* `amongSitesDistMat.R`
* `anova.R`
* `checks.R`
* `cov_betahat_adjust.R`
* `cov_initial_search.R`
* `cov_initial_search_glm.R`
* `cov_matrix.R`
* `cov_vector.R`
* `create_netgeometry.R`
* `createBinaryID.R`
* `get_anisotropy_corrected.R`
* `get_cholprods.R`
* `get_cov_matrix.R`
* `get_cov_vector.R`
* `get_data_object.R`
* `get_data_object_glm.R`
* `get_dist_object.R`
* `get_dist_pred_object.R`
* `get_dist_predbk_object.R`
* `get_eigenprods.R`
* `get_model_stats.R`
* `get_model_stats_glm.R`
* `get_sf_obj.R`
* `get_Torgegram_initial_object.R`
* `get.rid.fc.R`
* `getObsRelationshipsDF.R`
* `getPredRelationshipsDF.R`
* `gloglik_products.R`
* `gloglik.R`
* `initial.R`
* `initial_NA.R`
* `laploglik.R`
* `laploglik_products.R`
* `local.R`
* `loocv.R`
* `loocv_glm.R`
* `optim.R`
* `orig2optim.R`
* `optim2orig.R`
* `params.R`
* `partition.R`
* `predict.R`
* `predict_glm.R`
* `random.R`
* `restruct_ssn_missing.R`
* `Torgegram.R`
* `transform_anis.R`
* `use_gloglik.R`
* `use_laploglik.R`
* `utils.R`
