### ISSUE TITLE
SSN2 beta regression error

### ISSUE THREAD

**Issue by niallgclancy** [USEPA/SSN2#26]
Hi Mike and team,

I am running into an error when running a beta regression with SSN2. I have run some binomial regressions on different response variables in the same SSN object, and those worked just fine. So, I'm not sure what is going on. The error message is
 "Error: Convergence problem. Try using a different family, removing extreme observations, rescaling the response variable (if continuous), fixing ie at a known, non-zero value (via spcov_initial), or fixing dispersion at one (via dispersion_initial)."

I have made sure that 0s and 1s are converted to 0.000001 and 0.999999 for the beta regression. A histogram of the response variable also shows a fairly even spread of values between 0 and 1, so I don't think there are any issues with extreme observations. Any insights on this?

If you want to reproduce the error, my files and code are all at:  https://github.com/niallgclancy/persistence
The appropriate r file is "persistSSN.R"

**Comment by niallgclancy** [comment]
Update: I attempted to use spmodel alone and that seemed to work...something about SSN2 beta regression isn't working the same way. The relevant code in "persistSSN.R" is section 2 starting on line 173.

**Comment by michaeldumelle** [comment]
Thanks @niallgclancy ! I'll have a response here shortly.

**Comment by michaeldumelle** [comment]
@niallgclancy can you try a few things out and see if they work?

1. Set a minimum value of 0.001 and a maximum value of 0.999 (these are less extreme than the cutoffs you imposed).
2. Try running without a nugget `nugget_type = "none"`.
3. Try fixing dispersion at a value

```r
disp_init <- dispersion_initial(family = "beta", dispersion = 1, known = "dispersion")
```
If nothing there works, can you send me a minimally reproducible example I can spin up on my end? Some advice for that is [linked here](https://forum.posit.co/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one/5219).

**Comment by niallgclancy** [comment]
Well, that was an embarrassingly simple fix...using 0.001 and 0.999 did the trick. Thanks!

**Comment by michaeldumelle** [comment]
Glad to hear that worked @niallgclancy ! The beta regression models can be a bit numerically challenging when there are several response values that are very close to zero or one, so giving those boundaries a bit of cushion (e.g., as you did here going from 0.000001 to 0.001) can sometimes be helpful.
