### ISSUE TITLE
has the additive.function been removed form SSN2?

### ISSUE THREAD

**Issue by KGBrennan** [USEPA/SSN2#3]
Hi there, seems like there is not a corresponding additive.function() in this SSN2 Package. Wondering how we might generate afv's while using SSN2? 

I have tried setting fromate_additive = T with names_additive = "Attribute_Name" but I get an Error: that the object 'Attribute_Name' not found. Unfortunately, I can't seem to see any description in the CRAN pdf of how afv's can be generated. Might be useful for for other folks migrating to this new Package. 

Any advice would be greatly appreciated, thank you for your time.

**Comment by pet221** [comment]
Hi @KGBrennan - yes, additive.function() has not been included in SSN2. We're working on a new R package, SSNbler, which will replace most of the functionality in STARS and a new version of the function will sit there. The plan is to have the first version of SSNbler ready in the first quarter of 2024. Until then, you can either create those additive function values in ArcGIS Desktop (not Pro) using the [STARS tools](https://www.fs.usda.gov/research/rmrs/projects/stars-ssn#software-and-data) or create them using the SSN package. SSN has been archived on CRAN, but the latest release (1.1.18) along with all of its dependencies is available on the [SSN](https://github.com/jayverhoef/SSN/releases) github repositiory. You'll need to import the data from the .ssn directory, create the additive function values, and then save those changes to file using writeSSN().

**Comment by KGBrennan** [comment]
Good to know! Looking forward to seeing SSNbler. Thanks @pet221.
